### ISSUE TITLE
About demo error

### ISSUE THREAD

**Issue by xhzhong524** [FaceDetect/jointCascade_py#14]
I have follow the instructions, but when I run the
>  python -W ignore ./demo_detect.py ../config/afw_model/train.model ../config/pos.jpg

shows error like this:
Traceback (most recent call last):
  File "./demo_detect.py", line 98, in <module>
    main(sys.argv[1:])
  File "./demo_detect.py", line 95, in main
    detect_jpg(detector, args[1])    
  File "./demo_detect.py", line 45, in detect_jpg
    rects, confs = detector.detect(imgArr, 1.1, 2)
  File "./../cascade/cascade.py", line 120, in detect
    initShape)
  File "./../cascade/carm/boostCart.py", line 258, in validate
    initShape)
  File "./../cascade/carm/cart.py", line 291, in validate
    point_a = shape[feaType[1]]
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

Does anyone know how to fix this?

**Comment by zzw1123** [comment]
same error occurs to me ,have you solved them??
@xhzhong524

**Comment by wapping** [comment]
feaType = feaType.astype(int)
