### ISSUE TITLE
Can the code run in win?

### ISSUE THREAD

**Issue by weiyt2014** [FaceDetect/jointCascade_py#7]
the code can run in win?

**Comment by weiyt2014** [comment]
in win, I run the code. it has a mistake -"ImportError: numpy.core.multiarray failed to import

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\jointCascade_py-master\jointCascade_py-master\demo\demo_detect.py", line 6, in <module>
    import cv2
ImportError: numpy.core.multiarray failed to import"
I hope to get suggestions!Thanks very much!

**Comment by GarrickLin** [comment]
have you installed numpy for python in win environment?

**Comment by samuel1208** [comment]
I'm sorry. I just only test the code on Unbuntu

**Comment by weiyt2014** [comment]
can your testing time including  detection and alignment reach 30ms ? I see the paper is less 30ms

**Comment by GarrickLin** [comment]
it takes 6~7s in my machine by using samuel's model

**Comment by weiyt2014** [comment]
The speed cann't be accepted!The slow is slow!

**Comment by weiyt2014** [comment]
Can the code run in win?

**Comment by GarrickLin** [comment]
you might optimize it yourself, I just run the code in windows, I am trying to transplant the code into C++. and someone is doing this work, you can have a look at [luoyetx/JDA](https://github.com/luoyetx/JDA)

**Comment by weiyt2014** [comment]
Thanks very much!

**Comment by weiyt2014** [comment]
这个问题有遇到没？网上找了好久也没解决，请教一下啊！
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\jointCascade_py-master\jointCascade_py-master\demo\demo_detect.py", line 14, in <module>
    from cascade import *
  File "C:\Users\Administrator\Desktop\jointCascade_py-master\jointCascade_py-master\demo/../cascade__init__.py", line 1, in <module>
    from cascade import *
  File "C:\Users\Administrator\Desktop\jointCascade_py-master\jointCascade_py-master\demo/../cascade\cascade.py", line 7, in <module>
    from dator   import *
  File "C:\Users\Administrator\Desktop\jointCascade_py-master\jointCascade_py-master\demo/../dator__init__.py", line 1, in <module>
    from data   import *
  File "C:\Users\Administrator\Desktop\jointCascade_py-master\jointCascade_py-master\demo/../dator\data.py", line 6, in <module>
    from reader import *
  File "C:\Users\Administrator\Desktop\jointCascade_py-master\jointCascade_py-master\demo/../dator\reader.py", line 5, in <module>
    from scipy.ndimage.interpolation import zoom
  File "C:\Python27\lib\site-packages\scipy\ndimage__init__.py", line 172, in <module>
    from .filters import *
  File "C:\Python27\lib\site-packages\scipy\ndimage\filters.py", line 37, in <module>
    from scipy.misc import doccer
  File "C:\Python27\lib\site-packages\scipy\misc__init__.py", line 47, in <module>
    from scipy.special import comb, factorial, factorial2, factorialk
  File "C:\Python27\lib\site-packages\scipy\special__init__.py", line 548, in <module>
    from .basic import *
  File "C:\Python27\lib\site-packages\scipy\special\basic.py", line 17, in <module>
    from . import orthogonal
  File "C:\Python27\lib\site-packages\scipy\special\orthogonal.py", line 90, in <module>
    from scipy import linalg
  File "C:\Python27\lib\site-packages\scipy\linalg__init__.py", line 159, in <module>
    from .misc import *
  File "C:\Python27\lib\site-packages\scipy\linalg\misc.py", line 5, in <module>
    from . import blas
  File "C:\Python27\lib\site-packages\scipy\linalg\blas.py", line 145, in <module>
    from scipy.linalg import _fblas
ImportError: DLL load failed: 找不到指定的模块。
求指教一下！

**Comment by GarrickLin** [comment]
it might be a version problem
google `from scipy.linalg import _fblas ImportError: DLL load failed`

**Comment by weiyt2014** [comment]
对了，python的版本必须和numpy、scikit-learn、scipy版本保持一致吗？我的python是2.7.10版本的，但是对应的64位的这几个版本没有找到啊？求指教一下

**Comment by weiyt2014** [comment]
现在配置到没问题了，没有错误了，但是好像看不到检测效果！执行demo_detect会有这样的提示：
[[Usage]]::
    C:\Users\Administrator\Desktop\jointCascade_py-master\jointCascade_py-master\demo\demo_detect.py [Paras] train.model test.jpg
[[Paras]]::
    help|h : Print the help information 
求指教一下！

**Comment by weiyt2014** [comment]
对了，你好，我问一下，你那个python版本的jointcascade那个检测代码能看到定位效果吗？我这只能看到的是那个检测结果，时间是5s左右，大致和你运行的时间一样！

At 2015-09-21 15:39:26, "XianyanLin" notifications@github.com wrote:

it might be a version problem
google from scipy.linalg import _fblas ImportError: DLL load failed

**Comment by GarrickLin** [comment]
不能
